(library
 (name vyakarana_lib)
 (libraries unix str)
 (modules
    proof_graph
    event
    om_parser
    setu_shabda
    setu_classify
    setu
    anuvada
    socket
   yantra_types
   yantra_tokeniser
   yantra_arity
   yantra_sentence_parser
   yantra_expr_parser
   yantra_tantra_file
   yantra_index
   yantra_ops
   yantra_eval_primitives
   yantra_pipeline_ops
   yantra_eval
   yantra))
