open Proof_graph

(* ── naming convention ────────────────────────────────────────────────────────
   lua-setu.shabda: const-naming: kebab-to-upper-snake
   "cam-pitch-min" -> "CAM_PITCH_MIN"
   All setu key->constant mappings are derived by this rule — no lookup table. *)

let kebab_to_upper_snake (key : string) : string =
  String.uppercase_ascii (String.concat "_" (String.split_on_char '-' key))

(* ── substitution ─────────────────────────────────────────────────────────────
   Substitute UPPER_SNAKE placeholders in a Lua body using setu values.
   Keys are derived by rule. Longer keys substituted first to avoid prefix clash
   (e.g. CAM_PITCH_MIN before CAM_PITCH, COLOR_BOND_SEL before COLOR_BOND).
   Color values (#rrggbb) are wrapped in single quotes for Lua string literals. *)

let subst (setu : (string * string) list) (body : string) : string =
  (* sort by descending key length so longer/more-specific keys win *)
  let sorted = List.sort (fun (a,_) (b,_) -> compare (String.length b) (String.length a)) setu in
  List.fold_left (fun acc (key, raw_value) ->
    let value = String.trim raw_value in
    if String.length value = 0 then acc
    else begin
      let lua_const = kebab_to_upper_snake key in
      let lua_value =
        if String.length value > 0 && value.[0] = '#' then "'" ^ value ^ "'"
        else value
      in
      let re = Str.regexp_string lua_const in
      Str.global_replace re lua_value acc
    end
  ) body sorted

(* ── intent krama walker ──────────────────────────────────────────────────────
   Reads graph-viz-intent's sthita edges in declaration order.
   For each target node, looks up "node-key-<target>" in setu to get the
   lua block key. Emits blocks in that order.
   lua-update and lua-draw are always appended as the composite lifecycle tail. *)

let intent_block_keys (k : proof_graph) (setu : (string * string) list) : string list =
  match Hashtbl.find_opt k.nodes "graph-viz-intent" with
  | None -> []
  | Some intent_node ->
    (* collect sthita edges in declaration order (edges are stored in parse order) *)
    let sthita_targets = List.filter_map (fun e ->
      if e.source = "graph-viz-intent" && e.relation = Sthita then Some e.target
      else None
    ) intent_node.edges in
    (* for each target, look up node-key-<target> in setu; keep non-empty keys *)
    List.filter_map (fun target ->
      let key_name = "node-key-" ^ target in
      match List.assoc_opt key_name setu with
      | Some v when String.trim v <> "" -> Some (String.trim v)
      | _ -> None
    ) sthita_targets

(* ── composer ─────────────────────────────────────────────────────────────────
   All knowledge comes from the graph.
   graph-viz-setu.shabda  supplies constants and node-to-lua-key mapping.
   graph-viz-lua.shabda   supplies lua code blocks, globals, init, trampolines.
   graph-viz-intent.om    supplies krama order via sthita edges in declaration order.
   No hardcoded block order in OCaml. No hardcoded constant names. *)

let compose_graph_viz_from_setu (k : proof_graph) (_input : string) : unit =
  let setu = Setu.read_shabda k "graph-viz-setu" in
  let lua  = Setu.read_shabda k "graph-viz-lua"  in

  let get_setu key fb = match List.assoc_opt key setu with
    | Some v when String.trim v <> "" -> String.trim v
    | _ -> fb in

  let get_lua key fb = match List.assoc_opt key lua with
    | Some v when String.trim v <> "" -> String.trim v
    | _ -> fb in

  (* substitute setu constants into a lua body by rule *)
  let body key = subst setu (get_lua key "") in

  (* ── header ── *)
  let app_name = get_setu "app-name" "graph-viz" in
  Printf.printf "-- generated by prayoga (graph-viz-lua.om + graph-viz-setu.om)\n";
  Printf.printf "-- const-naming: kebab-to-upper-snake (lua-scope.om)\n";
  Printf.printf "-- block-order: from graph-viz-intent sthita edges (krama)\n";
  Printf.printf "-- app: %s\n\n" app_name;

  (* ── globals: file-level constants from lua-globals key ── *)
  let globals_tmpl = get_lua "lua-globals" "" in
  if String.length globals_tmpl > 0 then begin
    (* expand \n literals in the single-line globals template *)
    let globals = Str.global_replace (Str.regexp_string "\\n") "\n" globals_tmpl in
    print_string (subst setu globals);
    print_string "\n\n"
  end;

  (* ── blocks: emit in krama order from intent sthita edges ── *)
  let block_keys = intent_block_keys k setu in
  (* always append lua-update and lua-draw as the lifecycle tail *)
  let all_keys = block_keys @ ["lua-update"; "lua-draw"] in
  List.iter (fun key ->
    let b = body key in
    if String.length (String.trim b) > 0 then begin
      print_string b;
      print_newline ()
    end
  ) all_keys;

  (* ── on_init: lifecycle hook from lua-init key ── *)
  let init_body = body "lua-init" in
  if String.length (String.trim init_body) > 0 then begin
    print_string init_body;
    print_newline ()
  end;

  (* ── trampolines: on_update/on_draw from lua-trampolines key ── *)
  let tramp_body = body "lua-trampolines" in
  if String.length (String.trim tramp_body) > 0 then
    print_string tramp_body
  else begin
    Printf.printf "function on_update(dt) update(dt) end\n";
    Printf.printf "function on_draw()      draw()     end\n"
  end
