-- generated by prayoga (graph-viz-lua.om + graph-viz-setu.om)
-- const-naming: kebab-to-upper-snake (lua-scope.om)
-- block-order: from graph-viz-intent sthita edges (krama)
-- app: vyakarana-graph

local WIDTH, HEIGHT = 1400, 900
local PANEL_W = 380

local state = {
  t = 0.0,
  frame = 0,
  nodes = {}, edges = {},
  node_index = {}, edge_seen = {},
  hover = nil, sel = nil, dragging = nil,
  query_text = '',
  chat_lines = {},
  activated = {},
}

local function clamp(x, lo, hi)
  if x < lo then return lo elseif x > hi then return hi else return x end
end

-- physics simulation state (used by lua-physics and lua-seed)
local sim_alpha = 1.0
local node_degree = {}
local cam = {
  dist       = 45.0,
  yaw        = 0.0,
  pitch      = 0.38,
  tx = 0.0, ty = 0.0, tz = 0.0,
  fovy       = 45.0,
  zoom_fac   = 0.88,
  zoom_min   = 5.0,
  zoom_max   = 200.0,
  pan_speed  = 0.014,
  orbit_spd  = 0.006,
  pitch_min  = -1.55,
  pitch_max  = 1.55,
}

local function cam_pos()
  local cp = math.cos(cam.pitch)
  local sp = math.sin(cam.pitch)
  local cy = math.cos(cam.yaw)
  local sy = math.sin(cam.yaw)
  return
    cam.tx + cam.dist * cp * sy,
    cam.ty + cam.dist * sp,
    cam.tz + cam.dist * cp * cy
end

local function cam_axes()
  local cy = math.cos(cam.yaw)
  local sy = math.sin(cam.yaw)
  local cp = math.cos(cam.pitch)
  local sp = math.sin(cam.pitch)
  local fx = -cp * sy
  local fy = -sp
  local fz = -cp * cy
  local rx =  cy
  local ry =  0.0
  local rz = -sy
  local ux = ry*fz - rz*fy
  local uy = rz*fx - rx*fz
  local uz = rx*fy - ry*fx
  return rx,ry,rz, ux,uy,uz
end
local function cam_orbit(ddx, ddy)
  cam.yaw   = cam.yaw + ddx * cam.orbit_spd
  cam.pitch = clamp(cam.pitch + ddy * cam.orbit_spd, cam.pitch_min, cam.pitch_max)
end

local function cam_preset_top()
  cam.pitch = 1.55
  cam.yaw   = 0.0
end

local function cam_preset_bottom()
  cam.pitch = -1.55
  cam.yaw   = 0.0
end

local function cam_preset_front()
  cam.pitch = 0.0
  cam.yaw   = 0.0
end
-- domain → color table (derived from graph-viz-setu domain-color-* keys)
local DOMAIN_COLORS = {
  ['domain-physics']    = '#60a5fa',
  ['domain-math']       = '#60a5fa',
  ['domain-quantum']    = '#60a5fa',
  ['domain-fluid']      = '#60a5fa',
  ['domain-language']   = '#22d3ee',
  ['domain-ocaml']      = '#22d3ee',
  ['domain-lua']        = '#22d3ee',
  ['domain-biology']    = '#34d399',
  ['domain-chemistry']  = '#34d399',
  ['domain-sangeetham'] = '#f472b6',
  ['domain-finance']    = '#f59e0b',
  ['domain-3d']         = '#f59e0b',
  ['domain-raylib']     = '#f59e0b',
}

local function color_of_node(gn)
  for _, e in ipairs(gn.edges or {}) do
    if e.relation == 'sthita' then
      local c = DOMAIN_COLORS[e.target]
      if c then return c end
    end
  end
  -- session graph nodes always amber
  if string.sub(gn.name or '', 1, 6) == 'graph-' then return '#f59e0b' end
  return '#60a5fa'
end

local function spiral_pos(i, n)
  local golden = 2.39996322972865332
  local r = 18.0 * math.sqrt((i + 1) / n)
  local theta = i * golden
  return r * math.cos(theta), (i - n * 0.5) * 1.2, r * math.sin(theta)
end

local function seed_from_graph(g)
  state.nodes = {}; state.edges = {}
  state.node_index = {}; state.edge_seen = {}
  local nodes_list = g.nodes or {}
  local n = #nodes_list
  for i, gn in ipairs(nodes_list) do
    local x, y, z = spiral_pos(i - 1, n)
    table.insert(state.nodes, {
      id     = gn.name,
      x = x, y = y, z = z,
      vx = 0, vy = 0, vz = 0,
      fx = 0, fy = 0, fz = 0,
      satya  = gn.satya or 0.5,
      energy = (gn.satya or 0.5) * 0.9,
      color  = color_of_node(gn),
    })
    state.node_index[gn.name] = i
  end
  for i, gn in ipairs(nodes_list) do
    for _, e in ipairs(gn.edges or {}) do
      local j = state.node_index[e.target]
      if j and j ~= i then
        -- deduplicate undirected edges
        local lo = math.min(i, j)
        local hi = math.max(i, j)
        local key = lo * 100000 + hi
        if not state.edge_seen[key] then
          state.edge_seen[key] = true
          table.insert(state.edges, {a = i, b = j, rel = e.relation or ''})
        end
      end
    end
  end
  state.edge_seen = nil  -- free dedup table
  -- build degree table for d3 link strength (physics_step uses it)
  build_degrees()
  sim_alpha = 1.0
end
local function build_degrees()
  node_degree = {}
  for i = 1, #state.nodes do node_degree[i] = 0 end
  for _, e in ipairs(state.edges) do
    node_degree[e.a] = (node_degree[e.a] or 0) + 1
    node_degree[e.b] = (node_degree[e.b] or 0) + 1
  end
end

local function physics_step(dt)
  -- alpha cooling: stop when settled (saves all CPU once graph is stable)
  if sim_alpha < 0.001 then return end
  sim_alpha = sim_alpha + (0 - sim_alpha) * 0.0228

  local nodes = state.nodes
  local n = #nodes
  -- clear forces
  for i = 1, n do
    local nd = nodes[i]
    nd.fx, nd.fy, nd.fz = 0, 0, 0
  end

  -- repulsion (many-body) — inverse-square with distanceMax cutoff
  -- O(n*k) where k = avg nodes within 22.0; forces scaled by alpha
  local rep_str  = 28.0
  local rep_soft = 4.0
  local rep_max2 = 22.0 * 22.0
  for i = 1, n do
    local a = nodes[i]
    for j = i + 1, n do
      local b = nodes[j]
      local dx = a.x - b.x
      local dy = a.y - b.y
      local dz = a.z - b.z
      local d2 = dx*dx + dy*dy + dz*dz
      if d2 < rep_max2 then
        local ld2 = d2 + rep_soft
        local f = rep_str * sim_alpha / ld2
        a.fx = a.fx + dx * f;  a.fy = a.fy + dy * f;  a.fz = a.fz + dz * f
        b.fx = b.fx - dx * f;  b.fy = b.fy - dy * f;  b.fz = b.fz - dz * f
      end
    end
  end

  -- link force (bond) — d3 style: degree-weighted strength, asymmetric bias
  for _, e in ipairs(state.edges) do
    local a, b = nodes[e.a], nodes[e.b]
    local dx = b.x - a.x + b.vx - a.vx
    local dy = b.y - a.y + b.vy - a.vy
    local dz = b.z - a.z + b.vz - a.vz
    local dist = math.sqrt(dx*dx + dy*dy + dz*dz + 0.0001)
    -- d3 link strength = 1 / min(degree_a, degree_b)
    local da = math.max(node_degree[e.a] or 1, 1)
    local db = math.max(node_degree[e.b] or 1, 1)
    local strength = 1.0 / math.min(da, db)
    local l = (dist - 8.0) / dist * sim_alpha * strength
    dx = dx * l;  dy = dy * l;  dz = dz * l
    -- bias: fraction of correction applied to each end (proportional to degree)
    local bias = da / (da + db)
    b.fx = b.fx - dx * bias;      b.fy = b.fy - dy * bias;      b.fz = b.fz - dz * bias
    a.fx = a.fx + dx * (1 - bias); a.fy = a.fy + dy * (1 - bias); a.fz = a.fz + dz * (1 - bias)
  end

  -- center force — weak pull toward origin to prevent drift
  local center_str = 0.05 * sim_alpha
  for i = 1, n do
    local nd = nodes[i]
    nd.fx = nd.fx - nd.x * center_str
    nd.fy = nd.fy - nd.y * center_str
    nd.fz = nd.fz - nd.z * center_str
  end

  -- integrate: semi-implicit Euler + velocity decay (d3 velocityDecay)
  for i = 1, n do
    local nd = nodes[i]
    nd.vx = (nd.vx + nd.fx) * 0.55
    nd.vy = (nd.vy + nd.fy) * 0.55
    nd.vz = (nd.vz + nd.fz) * 0.55
    nd.x  = nd.x + nd.vx
    nd.y  = nd.y + nd.vy
    nd.z  = nd.z + nd.vz
  end
end
local function screen_delta_to_world(sdx, sdy)
  local rx,ry,rz, ux,uy,uz = cam_axes()
  local s = cam.dist * 0.28
  return
    rx * sdx * s + ux * (-sdy) * s,
    ry * sdx * s + uy * (-sdy) * s,
    rz * sdx * s + uz * (-sdy) * s
end

local function pick_hover(mx, my)
  -- guard: mouse in panel → no picking
  if mx >= WIDTH - PANEL_W then return nil end
  local cx, cy_c, cz = cam_pos()
  local rx,ry,rz, ux,uy,uz = cam_axes()
  local fcp = math.cos(cam.pitch)
  local fsp = math.sin(cam.pitch)
  local fsy = math.sin(cam.yaw)
  local fcy = math.cos(cam.yaw)
  local fx = -fcp * fsy
  local fy = -fsp
  local fz = -fcp * fcy
  local tan_half = math.tan(math.rad(cam.fovy) * 0.5)
  local vp_w = WIDTH - PANEL_W
  local aspect = vp_w / HEIGHT
  local best_i, best_d2 = nil, 44 * 44
  for i, n in ipairs(state.nodes) do
    local wx = n.x - cx
    local wy = n.y - cy_c
    local wz = n.z - cz
    local vx = wx*rx + wy*ry + wz*rz
    local vy = wx*ux + wy*uy + wz*uz
    local vz = wx*fx + wy*fy + wz*fz
    if vz < -0.1 then
      local sx = (-vx/(-vz)/(tan_half*aspect))*vp_w*0.5 + vp_w*0.5
      local sy = (-vy/(-vz)/tan_half)*HEIGHT*0.5 + HEIGHT*0.5
      local ddx, ddy = sx - mx, sy - my
      local d2 = ddx*ddx + ddy*ddy
      if d2 < best_d2 then best_d2 = d2; best_i = i end
    end
  end
  return best_i
end
function update(dt)
  state.t     = state.t + dt
  state.frame = state.frame + 1

  local mx, my   = input:mouse_pos()
  local clicked  = input:mouse_clicked()
  local down     = input:mouse_down()
  local rdown    = input:mouse_right_down()
  local ddx, ddy = input:mouse_delta()
  local wheel    = input:mouse_wheel()

  -- zoom (graph-camera-interaction.om: zoom-kriya)
  if wheel ~= 0 then
    cam.dist = clamp(cam.dist * (cam.zoom_fac ^ (-wheel)), cam.zoom_min, cam.zoom_max)
  end

  -- preset views (graph-camera-interaction.om: preset-top/bottom/front-kriya)
  if input:key_pressed('1') then cam_preset_top()    end
  if input:key_pressed('2') then cam_preset_bottom() end
  if input:key_pressed('3') then cam_preset_front()  end

  -- orbit (graph-camera-interaction.om: orbit-kriya, right-button-ahara)
  if rdown and not down then
    cam_orbit(ddx, ddy)
  end

  -- hover picking (graph-hover-picking.om)
  state.hover = pick_hover(mx, my)

  -- click → select + drag start (graph-drag-interaction.om: drag-start-kriya)
  if clicked then
    if state.hover then
      state.dragging = state.hover
      state.sel      = state.hover
      -- click-query: fire engine query for selected node (graph-click-query.om)
      if engine:available() then
        local n = state.nodes[state.hover]
        if n then
          local r = engine:query(n.id)
          if r and r.ok then
            table.insert(state.chat_lines, {role='engine', text='['..n.id..'] '..r.answer})
            state.activated = {}
            for _, id in ipairs(r.activated or {}) do
              state.activated[id] = true
            end
            -- trim chat log to last 40 lines
            while #state.chat_lines > 40 do
              table.remove(state.chat_lines, 1)
            end
          end
        end
      end
    else
      state.dragging = nil
    end
  end

  -- left drag: node drag or camera pan (graph-drag-interaction.om)
  if down and not rdown then
    if state.dragging then
      -- drag-step-kriya: pull node, propagate through bonds; reheat alpha so physics wakes
      sim_alpha = math.max(sim_alpha, 0.3)
      local fx, fy, fz = screen_delta_to_world(ddx, ddy)
      local n = state.nodes[state.dragging]
      n.vx = n.vx + fx;  n.vy = n.vy + fy;  n.vz = n.vz + fz
      for _, e in ipairs(state.edges) do
        local other = nil
        if e.a == state.dragging then other = e.b
        elseif e.b == state.dragging then other = e.a end
        if other then
          local nb = state.nodes[other]
          nb.vx = nb.vx + fx * 0.22
          nb.vy = nb.vy + fy * 0.22
          nb.vz = nb.vz + fz * 0.22
        end
      end
    else
      -- pan-step-kriya
      local rx, ry, rz, ux, uy, uz = cam_axes()
      local ps = cam.dist * cam.pan_speed
      cam.tx = cam.tx - (rx*ddx - ux*ddy) * ps
      cam.ty = cam.ty - (ry*ddx - uy*ddy) * ps
      cam.tz = cam.tz - (rz*ddx - uz*ddy) * ps
    end
  end

  if not down then state.dragging = nil end

  -- text input for chat query box (graph-click-query.om: chat-yukta)
  local typed = input:chars()
  if typed and #typed > 0 then
    state.query_text = state.query_text .. typed
  end
  if input:key_pressed('backspace') and #state.query_text > 0 then
    state.query_text = string.sub(state.query_text, 1, #state.query_text - 1)
  end
  -- submit query on Enter (graph-query-cycle.om)
  if input:key_pressed('enter') and #state.query_text > 0 then
    local q = state.query_text
    state.query_text = ''
    table.insert(state.chat_lines, {role='user', text=q})
    if engine:available() then
      local r = engine:query(q)
      if r and r.ok then
        table.insert(state.chat_lines, {role='engine', text=r.answer})
        state.activated = {}
        for _, id in ipairs(r.activated or {}) do
          state.activated[id] = true
        end
      else
        table.insert(state.chat_lines, {role='engine', text='(no response)'})
      end
    else
      table.insert(state.chat_lines, {role='engine', text='(engine not available)'})
    end
    while #state.chat_lines > 40 do table.remove(state.chat_lines, 1) end
  end

  -- physics substep throttle (graph-spring-interaction.om: velocity-step-kriya)
  if state.frame % 1 == 0 then
    physics_step(dt * 1)
  end
end
function draw()
  canvas:rect(0, 0, WIDTH, HEIGHT, '#05080f')
  local cx, cy, cz = cam_pos()
  canvas:begin_3d(cx, cy, cz, cam.tx, cam.ty, cam.tz, cam.fovy)

  -- reference grid (graph-container.om: viewport-yukta)
  for gi = -8, 8 do
    local gv = gi * 5.0
    canvas:line3d(gv, -5.0, -40.0, gv, -5.0,  40.0, '#0e1e2e')
    canvas:line3d(-40.0, -5.0, gv, 40.0, -5.0, gv,  '#0e1e2e')
  end

  -- edges (graph-edge-visual.om: cylinder-swarupa, glow-phala)
  for _, e in ipairs(state.edges) do
    local a, b   = state.nodes[e.a], state.nodes[e.b]
    local is_sel = (state.sel == e.a or state.sel == e.b)
    local is_act = state.activated[a.id] and state.activated[b.id]
    local color  = is_act and '#fbbf24' or (is_sel and '#7ab8f5' or '#1e3a5a')
    local r      = is_sel and 0.16 or 0.08
    canvas:cylinder3d(a.x,a.y,a.z, b.x,b.y,b.z, r, color)
  end

  -- nodes (graph-node-visual.om: sphere-swarupa, satya-yukta, energy-yukta)
  for i, n in ipairs(state.nodes) do
    local pulse = 1.0 + math.sin(state.t * 3.2 + n.energy * 6.28318) * 0.09
    local r     = clamp(n.satya * 1.85 * pulse, 0.35, 1.8)
    -- activity glow (graph-activity-glow.om: glow-kriya)
    if state.activated[n.id] then
      canvas:sphere(n.x, n.y, n.z, r * 1.6, '#fbbf24')
    end
    local col = (i == state.hover) and '#ffffff' or n.color
    canvas:sphere(n.x, n.y, n.z, r, col)
  end

  canvas:end_3d()

  -- side panel (graph-click-query.om: chat-yukta)
  local px = WIDTH - PANEL_W
  canvas:rect(px, 0, PANEL_W, HEIGHT, '#040810')
  canvas:text(px+16,  18, 'vyakarana graph',   20, '#cde0f8')
  canvas:text(px+16,  42, #state.nodes..' nodes  '..#state.edges..' bonds', 12, '#486888')

  -- selected node info
  if state.sel then
    local n = state.nodes[state.sel]
    canvas:text(px+16, 68, n.id,  15, n.color)
    canvas:text(px+16, 88, 'satya '..string.format('%.3f', n.satya), 12, '#486888')
  end

  -- chat log (query-turn-state.om: question-yukta, activated-nodes-yukta)
  local chat_top = 116
  local line_h   = 18
  local max_lines = math.floor((HEIGHT - chat_top - 80) / line_h)
  local start_i   = math.max(1, #state.chat_lines - max_lines + 1)
  for li = start_i, #state.chat_lines do
    local entry = state.chat_lines[li]
    local col   = entry.role == 'user' and '#cde0f8' or '#486888'
    local prefix = entry.role == 'user' and '> ' or '  '
    local y = chat_top + (li - start_i) * line_h
    -- wrap long lines crudely at ~40 chars
    local text = prefix .. string.sub(entry.text, 1, 42)
    canvas:text(px+12, y, text, 12, col)
  end

  -- query input box
  local qy = HEIGHT - 68
  canvas:rect(px+8, qy - 4, PANEL_W - 16, 24, '#05080f')
  canvas:text(px+14, qy, '> '..state.query_text..'_', 14, '#cde0f8')

  -- controls hint
  canvas:text(px+12, HEIGHT-42, 'L-drag:pan/pull  R-drag:orbit', 11, '#486888')
  canvas:text(px+12, HEIGHT-26, 'wheel:zoom  1:top 2:bot 3:front', 11, '#486888')
end
function on_init()
  if engine:available() then
    local g = engine:session('graph-viz-dev')
    if g and g.nodes then
      seed_from_graph(g)
    end
  end
end
function on_update(dt) update(dt) end
function on_draw()      draw()     end