"""test_motion.py — verb semantics infrastructure: motion verbs, verb-concept chains,
auxiliary composites, and construction-level bindings.

Four layers of capability, all xfail until built:
  L1  verb-concept chain   — verb base form lands on a kosha concept, not dhatu loop
  L2  participle wiring    — -ing forms connected to dhatu system (swarupa→tinanta, janya→dhatu)
  L3  auxiliary composite   — "is moving" = single semantic verb unit (aux + participle)
  L4  verb-rate binding    — "V at X unit" binds X to the rate-concept of the verb
"""

import pytest

xfail = pytest.mark.xfail


# ══════════════════════════════════════════════════════════════════════════════
# Layer 1: verb-concept chain — verb base form → kosha concept
# ══════════════════════════════════════════════════════════════════════════════
# "accelerate" → acceleration works because word-node("accelerate") → acceleration.
# "move" → dhatu-move LOOPS. The verb-concept chain in emit-triples breaks
# when word-node(base) == dhatu (the neq guard filters it out).
# Fix: each physics verb needs a kosha concept to land on.


def test_L1_move_verb_concept(vy):
    """'moves' should extract displacement concept via verb-concept chain"""
    g = vy.bqg("a ball moves")
    satya = vy.subjects(g, pred="satya")
    assert "displacement" in satya, f"expected displacement in satya, got {satya}"


def test_L1_fall_verb_concept(vy):
    """'falls' should extract falling concept via verb-concept chain"""
    g = vy.bqg("a ball falls")
    satya = vy.subjects(g, pred="satya")
    assert "falling" in satya, f"expected falling in satya, got {satya}"


def test_L1_rotate_verb_concept(vy):
    """'rotates' should extract rotation concept"""
    g = vy.bqg("a disc rotates")
    satya = vy.subjects(g, pred="satya")
    assert "rotation" in satya, f"expected rotation in satya, got {satya}"


def test_L1_collide_verb_concept(vy):
    """'collides' should extract collision concept"""
    g = vy.bqg("a ball collides")
    satya = vy.subjects(g, pred="satya")
    assert "collision" in satya, f"expected collision in satya, got {satya}"


def test_L1_travel_verb_concept(vy):
    """'travels' should extract displacement concept (synonym of move)"""
    g = vy.bqg("a car travels")
    satya = vy.subjects(g, pred="satya")
    assert "displacement" in satya, f"expected displacement in satya, got {satya}"


@xfail(strict=True, reason="verb-concept: 'throw' resolves to dhatu-throw, not projectile concept")
def test_L1_throw_verb_concept(vy):
    """'thrown' should extract a projectile/motion concept"""
    g = vy.bqg("a ball was thrown")
    satya = vy.subjects(g, pred="satya")
    assert len(satya) > 0, "verb 'thrown' should extract a concept"


# ══════════════════════════════════════════════════════════════════════════════
# Layer 2: participle wiring — -ing forms in dhatu system
# ══════════════════════════════════════════════════════════════════════════════
# verb-moving and verb-rotating are legacy orphans: no swarupa→tinanta,
# no janya→dhatu-X. All other -ing forms (running, accelerating, etc.) are
# properly generated by kriya-nirmana. These two need fixing.


def test_L2_moving_is_tinanta(vy):
    """'moving' should be classified as tinanta (verb form)"""
    nd = vy.eval('(word-node "moving")')
    swarupa = vy.walk(nd, "swarupa")
    assert "tinanta" in swarupa, f"'moving' node {nd} missing swarupa→tinanta"


def test_L2_moving_janya_dhatu(vy):
    """'moving' should have janya edge back to dhatu-move"""
    nd = vy.eval('(word-node "moving")')
    janya = vy.walk(nd, "janya")
    assert "dhatu-move" in janya, f"'moving' node {nd} missing janya→dhatu-move"


def test_L2_rotating_is_tinanta(vy):
    """'rotating' should be classified as tinanta"""
    nd = vy.eval('(word-node "rotating")')
    swarupa = vy.walk(nd, "swarupa")
    assert "tinanta" in swarupa, f"'rotating' node {nd} missing swarupa→tinanta"


def test_L2_moving_emits_tense(vy):
    """'moving' should emit vartamana-kaala tense, like 'running' does"""
    g = vy.bqg("the ball is moving")
    # 'running' correctly emits vartamana-kaala; 'moving' should too
    assert vy.has_triple(g, subj="moving", pred="vartamana-kaala") or \
        vy.has_triple(g, pred="vartamana-kaala")


# ══════════════════════════════════════════════════════════════════════════════
# Layer 3: auxiliary composites — "is moving" = single verb unit
# ══════════════════════════════════════════════════════════════════════════════
# BQG processes word-by-word. "is" → copula, "moving" → separate token.
# The composite "is moving" should be recognised as present continuous,
# "was moving" as past continuous (→ initial state via kaala-avastha).


@xfail(strict=True, reason="auxiliary-composite: 'is moving' not recognised as present continuous verb")
def test_L3_is_moving_composite(vy):
    """'is moving at 5' — auxiliary+participle should act as single verb"""
    g = vy.bqg("a ball is moving at 5 m/s")
    sankhya = vy.triple_map(g, pred="sankhya")
    # must bind to velocity concept, not just the unit node
    assert "velocity" in sankhya, f"expected velocity in sankhya, got {sankhya}"


@xfail(strict=True, reason="auxiliary-composite: 'was moving' should signal past state via kaala-avastha")
def test_L3_was_moving_initial_state(vy):
    """'was moving at 5' — past continuous → initial-velocity via kaala-avastha"""
    g = vy.bqg("the ball was moving at 5 m/s")
    sankhya = vy.triple_map(g, pred="sankhya")
    # must bind to velocity concept (or initial-velocity), not just unit
    assert "initial-velocity" in sankhya or "velocity" in sankhya, \
        f"expected velocity concept in sankhya, got {sankhya}"


@xfail(strict=True, reason="auxiliary-composite: 'is rotating' not recognised as continuous verb")
def test_L3_is_rotating_composite(vy):
    """'is rotating at 3 rad/s' — angular velocity binding"""
    g = vy.bqg("a disc is rotating at 3 rad/s")
    sankhya = vy.triple_map(g, pred="sankhya")
    assert "angular-velocity" in sankhya, f"expected angular-velocity, got {sankhya}"


@xfail(strict=True, reason="auxiliary-composite: 'is falling' not recognised as continuous verb")
def test_L3_is_falling_composite(vy):
    """'is falling at 10 m/s' — velocity binding via fall verb"""
    g = vy.bqg("a ball is falling at 10 m/s")
    sankhya = vy.triple_map(g, pred="sankhya")
    assert "velocity" in sankhya, f"expected velocity in sankhya, got {sankhya}"


@xfail(strict=True, reason="auxiliary-composite: 'is accelerating at' binds unit not concept without composite")
def test_L3_is_accelerating_composite(vy):
    """'is accelerating at 3' — composite should bind like 'accelerates at 3'"""
    g = vy.bqg("a car is accelerating at 3 m/s2")
    sankhya = vy.triple_map(g, pred="sankhya")
    # "accelerates at" works via verb-concept. "is accelerating at" currently
    # binds to acceleration too (lucky: verb-concept chain works for accelerate).
    # But the composite should produce a SINGLE verb context, not copula + verb.
    # Test that the copula doesn't produce a spurious kaala triple on "car".
    copula_triples = [t for t in g if isinstance(t, list) and t[1] == "copula"]
    assert len(copula_triples) == 0, \
        f"composite 'is accelerating' should not leave orphan copula: {copula_triples}"


# ══════════════════════════════════════════════════════════════════════════════
# Layer 4: verb-rate binding — "V at X unit" → concept = X
# ══════════════════════════════════════════════════════════════════════════════
# "moves at 5 m/s" means velocity=5. The verb implies a concept (displacement),
# and "at X m/s" binds the RATE of that concept (velocity = d(displacement)/dt).
# The graph has kramanusara edges for this: velocity kramanusara→displacement.
# This layer tests the full binding chain: verb → concept → rate → sankhya.


@xfail(strict=True, reason="verb-rate: 'moves at 5 m/s' should bind velocity=5")
def test_L4_moves_at_velocity(vy):
    """'moves at 5 m/s' — motion verb + speed unit → velocity binding"""
    g = vy.bqg("a ball moves at 5 m/s")
    sankhya = vy.triple_map(g, pred="sankhya")
    assert "velocity" in sankhya, f"expected velocity in sankhya, got {sankhya}"


@xfail(strict=True, reason="verb-rate: 'falls at 10 m/s' should bind velocity=10")
def test_L4_falls_at_velocity(vy):
    """'falls at 10 m/s' — fall verb + speed unit → velocity binding"""
    g = vy.bqg("a ball falls at 10 m/s")
    sankhya = vy.triple_map(g, pred="sankhya")
    assert "velocity" in sankhya


@xfail(strict=True, reason="verb-rate: 'rotates at 3 rad/s' should bind angular-velocity=3")
def test_L4_rotates_at_angular_velocity(vy):
    """'rotates at 3 rad/s' — rotation verb + angular unit → angular-velocity"""
    g = vy.bqg("a disc rotates at 3 rad/s")
    sankhya = vy.triple_map(g, pred="sankhya")
    assert "angular-velocity" in sankhya, f"expected angular-velocity, got {sankhya}"


@xfail(strict=True, reason="verb-rate: 'travels at 30 m/s' should bind velocity=30")
def test_L4_travels_at_velocity(vy):
    """'travels at 30 m/s' — travel verb + speed → velocity"""
    g = vy.bqg("a car travels at 30 m/s")
    sankhya = vy.triple_map(g, pred="sankhya")
    assert "velocity" in sankhya


@xfail(strict=True, reason="verb-rate: 'thrown at 20 m/s' should bind initial-velocity=20")
def test_L4_thrown_at_initial_velocity(vy):
    """'was thrown at 20 m/s' — past tense throw → initial-velocity via kaala-avastha"""
    g = vy.bqg("a ball was thrown at 20 m/s")
    sankhya = vy.triple_map(g, pred="sankhya")
    assert "initial-velocity" in sankhya or "velocity" in sankhya


@xfail(strict=True, reason="verb-rate: 'collides at 5 m/s' should bind velocity=5")
def test_L4_collides_at_velocity(vy):
    """'collides at 5 m/s' — collision verb + speed → velocity"""
    g = vy.bqg("a ball collides at 5 m/s")
    sankhya = vy.triple_map(g, pred="sankhya")
    assert "velocity" in sankhya


# ── Layer 4 extended: verb + preposition constructions ───────────────────────
# Beyond "at", other prepositions bind different argument slots.


@xfail(strict=True, reason="verb-prep: 'falls from 10 m' should bind height=10")
def test_L4_falls_from_height(vy):
    """'falls from 10 m' — apadana (from) after fall → height binding"""
    g = vy.bqg("a ball falls from 10 m")
    sankhya = vy.triple_map(g, pred="sankhya")
    assert "height" in sankhya, f"expected height in sankhya, got {sankhya}"


@xfail(strict=True, reason="verb-prep: 'moves for 3 s' should bind time=3")
def test_L4_moves_for_time(vy):
    """'moves for 3 s' — sampradana (for) after motion verb → time binding"""
    g = vy.bqg("a ball moves for 3 s")
    sankhya = vy.triple_map(g, pred="sankhya")
    assert "time" in sankhya, f"expected time in sankhya, got {sankhya}"


# ══════════════════════════════════════════════════════════════════════════════
# End-to-end: full physics answers requiring motion verb infrastructure
# ══════════════════════════════════════════════════════════════════════════════


@xfail(strict=True, reason="e2e-motion: 'moves at' velocity not bound, KE computation fails")
def test_e2e_moves_at_momentum(vy):
    """proton moves at 2e6 m/s, mass given → find momentum"""
    r = vy.answer("a proton moves at 2e6 m/s. it has mass 1.67e-27 kg. find momentum")
    assert "3.34e-21" in r or "3.34" in r


@xfail(strict=True, reason="e2e-motion: 'is moving at' velocity not bound, KE computation fails")
def test_e2e_moving_at_kinetic_energy(vy):
    """electron is moving at 1e6 m/s, mass given → find KE"""
    r = vy.answer(
        "the electron has mass 9.109e-31 kg. it is moving at 1e6 m/s. find kinetic energy"
    )
    assert "4.5" in r


@xfail(strict=True, reason="e2e-motion: 'falls from' height not bound, PE computation fails")
def test_e2e_falls_from_pe(vy):
    """ball falls from 20 m, mass given → find PE"""
    r = vy.answer("a ball of mass 2 kg falls from 20 m. find potential energy")
    assert "392" in r or "400" in r


@xfail(strict=True, reason="e2e-motion: 'rotates at' angular velocity not bound")
def test_e2e_rotates_at_angular_momentum(vy):
    """disc rotates at 10 rad/s, moment of inertia given → find angular momentum"""
    r = vy.answer(
        "a disc has moment of inertia 0.5 kg*m2. it rotates at 10 rad/s. "
        "find angular momentum"
    )
    # L = I*omega = 0.5 * 10 = 5.0 — must be a computed result, not "no match"
    assert "no match" not in r.lower(), f"should compute angular momentum, got: {r}"
    assert "= 5" in r or "is 5" in r or r.strip().endswith("5")


@xfail(strict=True, reason="e2e-motion: 'travels at' + time → distance = v*t")
def test_e2e_travels_at_distance(vy):
    """car travels at 30 m/s for 10 s → distance = 300"""
    r = vy.answer("a car travels at 30 m/s for 10 s. find distance")
    assert "300" in r
